feat : 공지사항 앱 추가
LikeLion-11th-Domtory/Domtory_Server pull request #1
Opened 2023-11-24 06:32 UTC by bestfourteen14

### 🌟이슈 번호
- 
### 작업한 내용
- 공지사항 앱 추가
- 공지사항 기능 추가 (공지사항 전체 조회, 상세 조회, 제목으로 검색 기능)
- makemigration 및 base.py - project app에 'notice' 추가

2023-11-24 12:47 UTC, leehjhjhj requested changes
짜느라 고생하셨어요~ 리뷰한번 봐주세요

2023-11-24 12:47 UTC, leehjhjhj commented on notice/models.py
> +    content = models.TextField(default='')
null True 말고 default='' 로 해둔 이유가 있나요? 그리고 content를 Textfield로 선정한 이유도 궁금해요

2023-11-24 12:47 UTC, leehjhjhj commented on notice/views.py
> +class NoticeSearchView(generics.ListAPIView):
이거는 무슨 VIew인가요? 글 제목을 찾는 뷰인가요

2023-11-24 12:50 UTC, bestfourteen14 commented on notice/models.py
> +    content = models.TextField(default='')
content의 경우, 사진만 있고, 텍스트가 없을 경우, 크롤링 결과에 ''로 떠서 default = ''로 선정했습니다
null True도 가능하다면 그렇게 설정해도 될 것 같아요!

2023-11-24 12:52 UTC, bestfourteen14 commented on notice/views.py
> +class NoticeSearchView(generics.ListAPIView):
넵 공지사항 글 제목으로 추가한 view인데, 
지난 플젝에서 한번 사용했을 때, 프론트 측에서 구현해도 괜찮다고 했던 기억이 있어서 구현만 해두고, urls.py에는 추가하지 않았어요
프론트에 물어보고 이걸 사용하는게 더 편하다고 말하면 urls.py에도 추가할 생각입니다.

2023-11-25 01:27 UTC, leehjhjhj commented on notice/models.py
> +    content = models.TextField(default='')
TextField는 말씀대로  max_length를 가지고 있지 않아요. 그런데 현재 화면이 어떻게 나올지 몰라서 글자 제한수를 안 넣어도 되는지 모르겠군요. 후에 화면이 어떻게 설계되었는지 알아보고 바꿔도 좋을 것 같아요! 지금은 그대로 고고합시다

2023-11-25 01:28 UTC, leehjhjhj commented on notice/models.py
> +    content = models.TextField(default='')
그리고 저는 만약 객체가 존재하지 않다면 '' 보다는 null이 더 좋을 것 같아요. 후에 추가 코드를 넣기에도 편하거든요

2023-11-25 01:29 UTC, leehjhjhj commented on notice/views.py
> +class NoticeSearchView(generics.ListAPIView):
확실히 좋아요 코드리뷰 ㅋㅋ 내가 몰랐떤 부분 알게되는.. 제목 검색 구현도 좋을 것 같아요~~

2023-11-25 04:38 UTC, bestfourteen14 commented on notice/views.py
> +class NoticeSearchView(generics.ListAPIView):
이부분은 주석처리 해놓겠습니다~ 프론트에서 구현하는게 장점이 더 크다고 하네요!

2023-11-25 04:38 UTC, bestfourteen14 commented on notice/models.py
> +    content = models.TextField(default='')
넵 null=True로 바꿀게요!

2023-11-25 05:28 UTC, LeeSpect commented
수고하셨습니다! 저는 앞서 작성된 리뷰 외에 다른 리뷰 사항 없습니다.

2023-11-26 08:18 UTC, leehjhjhj approved these changes
늦어져서 죄송해요 수고하셨어요~

2023-11-26 11:33 UTC, LeeSpect approved these changes
수고하셨습니다!

2023-11-29 17:07 UTC, merged