Menu
LikeLion-11th-Domtory/Domtory_Server pull request #2
Opened 2023-11-24 06:57 UTC by LeeSpect

# Menu 기반 작업
### id, date_code, date_detail, breakfast, lunch, dinner 으로 Menu 모델 구성
### 날짜에 따라 아침/점심/저녁 메뉴 전부, 혹은 아침, 점심, 저녁 메뉴 중 하나를 보내주는 class view 구현

2023-11-24 12:43 UTC, leehjhjhj requested changes
짜느라 고생하셨어요~ 리뷰한번 봐주세요

2023-11-24 12:43 UTC, leehjhjhj commented on menu/models.py
> +    breakfast = models.CharField(max_length=1000)
1000?! 이유가 있는 수치인가요

2023-11-24 12:43 UTC, leehjhjhj commented on menu/views.py
> +        serializer = DinnerSerializer(menus, many=True)
VIew 다 좋은데 너무 중복되는 느낌이 있어요. 사실상 api 하나로 줄일 수 있을 것 같은데 어떻게 생각하세요? Serializer를 인자로 받는다면 하나로 줄 일 수 있을 것 같은데..

2023-11-24 13:00 UTC, bestfourteen14 commented on menu/views.py
> +        serializer = DinnerSerializer(menus, many=True)
> VIew 다 좋은데 너무 중복되는 느낌이 있어요. 사실상 api 하나로 줄일 수 있을 것 같은데 어떻게 생각하세요? Serializer를 인자로 받는다면 하나로 줄 일 수 있을 것 같은데..

'serializer = ~'부분을 제외하고는 다 동일해서 API 하나만 설정한 후 나머지는 serializer만 인자로 받아서 처리하면 된다는 말씀인거죠?

2023-11-25 01:25 UTC, leehjhjhj commented on menu/views.py
> +        serializer = DinnerSerializer(menus, many=True)
네 저는 그렇게하면 하나로 줄 일 수 있고, 쿼리파라미터로 아침점심저녁 구분하면 될 것 같아요.

2023-11-25 05:24 UTC, LeeSpect commented on menu/models.py
> +    breakfast = models.CharField(max_length=1000)
코파일럿이 추천해준 대로 넣었고 다른 의도는 없었어요

2023-11-25 05:25 UTC, LeeSpect commented on menu/views.py
> +        serializer = DinnerSerializer(menus, many=True)
그렇게 바꿔서 커밋 하겠습니다!

2023-11-25 05:30 UTC, bestfourteen14 reviewed
views.py만 바꾸면 바로 merge해도 될 거 같아요

2023-11-25 10:27 UTC, bestfourteen14 approved these changes
수고하셨어요! 추가 리뷰 사항 없습니다

2023-11-26 08:23 UTC, leehjhjhj requested changes
한번더 잠시 봐주세요! 궁금증들이 있어서,,,

2023-11-26 08:23 UTC, leehjhjhj commented on menu/serializers.py
> +class BreakfastSerializer(serializers.ModelSerializer):
오잉 ERD가 바뀌었었나요?

2023-11-26 08:23 UTC, leehjhjhj commented on menu/models.py
> +    breakfast = models.CharField(max_length=1000)
보통 1000으로 안하고 255, 512 이런 식으로 하긴 하는데 상관없을 것 같긴 해요

2023-11-26 08:23 UTC, leehjhjhj commented on menu/crawling_view.py
> +def crawling():
이거는 api인가요??

2023-11-26 11:22 UTC, LeeSpect commented on menu/crawling_view.py
> +def crawling():
넵 api로 호출하게 만들었어요.
api로 호출 안 하고 shell에서 직접 실행하게 바꿀까요? 코드가 정상 작동하는지 확인하는 과정에서 shell에서 직접 실행해봤었습니다.

2023-11-26 11:23 UTC, LeeSpect commented on menu/models.py
> +    breakfast = models.CharField(max_length=1000)
음 그럼 스탠다드 따라가야죠... 512로 바꿔놓을게요!

2023-11-26 11:29 UTC, LeeSpect commented on menu/serializers.py
> +class BreakfastSerializer(serializers.ModelSerializer):
네 저장하는 과정에서 문제가 있어서 ERD 수정했고, 저 fields 값은 date_code 누락된 걸 추가한 겁니다.
지금 수정된 ERD 노션에 업로드했습니다!

2023-11-28 02:33 UTC, leehjhjhj approved these changes
수고하셨습니당👍

2023-11-28 02:34 UTC, merged