[Feat] 쪽지 기능 구현
LikeLion-11th-Domtory/Domtory_Server pull request #82
Opened 2024-05-02 02:05 UTC by Zena0128

### 작업한 내용
- 쪽지 조회, 보내기, 차단 기능 구현

### 작업할 내용
- 어디서 시작된 쪽지인지 표시

2024-05-04 03:04 UTC, leehjhjhj requested changes
오우.. 막 들어오셨음에도 불구하고 코드가 우리 프로젝트에 잘 녹아들게끔 깔끔하게 적어주셨네요!
수고 많으셨습니다. 몇 가지만 고쳐서 다시 올려주시면 좋을 것 같아요! 크게
1. 시리얼라이저 쿼리
2. 필드명 _id
3. 단축어
를 고쳐주시면 더 좋은 코드가 될 것 같아요~ ~ ~ ~

2024-05-04 03:04 UTC, leehjhjhj commented on message/domains/message_models.py
> +    send_id = models.ForeignKey(Member, null=False, on_delete=models.CASCADE, verbose_name='송신자', related_name='message_sender')
회원과 쪽지는 생명주기를 같이하지 않기 때문에 CASCADE를 걸면 안될 것 같아요. 회원이 없어져도 쪽지는 남겨야 할 수 있으니깐 ..!

2024-05-04 03:04 UTC, leehjhjhj commented on message/domains/message_models.py
> +    recv_id = models.ForeignKey(Member, null=False, on_delete=models.CASCADE, verbose_name='수신자', related_name='message_receiver')
위와 같은 맥락입니다.

2024-05-04 03:04 UTC, leehjhjhj commented on message/domains/message_models.py
> +    body = models.TextField(default="", verbose_name='내용')
`TextFiled` 보다는 Charfieldf로 제한하는 것이 좋을 것 같아요. 효율성이나.. 아니면 이후에 코드 짤 때도.. (장고에서 textfield 뭐 안되는 게 있었는데 기억이 안 남)

2024-05-04 03:04 UTC, leehjhjhj commented on message/domains/message_block_models.py
> +    req_id = models.ForeignKey(Member, null=False, on_delete=models.CASCADE, verbose_name='발신자', related_name='block_sender')
django model에서 `_id` 로 필드명을 짖는 것은 비추천합니다. 왜냐하면 자동으로 _id가 붙기 때문이쥬
이렇게 생성하면 데이터베이스에서는 `req_id_id`로 생성됩니다..
그냥 풀네임으로 id 없이 필드명을 짓는 건 어떨까요?

2024-05-04 03:04 UTC, leehjhjhj commented on message/serializers/message_serializer.py
> +            new_messages = Message.objects.filter(Q(send_id = sender) & Q(recv_id = receiver) & Q(is_read = False))
밑의 코드를 보니깐, 이 시리얼라이저는 `many=True`로 다수의 데이터를 처리할 때 사용될 때도 있는 것 같아요.
이런 로직의 경우 sender와 receiver를 굳이 참조해서 객체를 꺼내올 필요는 없을 것 같아요. 그냥 id만 넣어줘도 괜찮을 듯!
만약 쪽지 개수가 50개인 리스트를 불러온다면.. 하나의 메시지마다 3개의 쿼리가 나간다고하면 너무 비효율적인 것 같아요!

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=receiver)
이것도 `get_object_or_404` 로 처리하면 try except문을 사용하지 않을 수 있어요.

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +    for smsg in sent_messages:
의미를 잘 모르겠는 단축어보다는 차라리 풀어쓰는게 더 좋은 경우도 많다고 하네요!
이런 경우는 풀어쓰는게 다른 사람들이 코드를 볼 때 더 좋을 것 같아요

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +def delete_messages(request, target_id):
여러 개의 데이터를 변환시키는 로직의 경우 `트랜잭션` 관리를 하면 더 좋은 코드가 될 수 있어요.
만약에 로직 중간에 서버가 꺼지거나 (만에 하나), 오류가 발생한다면 모든 쪽지가 삭제되지 않고, 중간까지만 is_deleted가 True 되어서 정합성에 이상이 생기겠지요?
장고ORM에서는 `commit()` 을 개발자가 명시적으로 표현하지 않기 때문에 `@transaction.atomic()` 라는 데코레이터를 쓰는데요, 한번 찾아보고 적용하면 좋을 것 같아요!!

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +    cands = []
cands가 뭘까요  ?

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +    for s, r in cands:
이것도 지나친 단축어인 것 같아요!

2024-05-04 03:04 UTC, leehjhjhj commented on message/services/message_block.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=target)
요놈도 그냥 `get_object_or_404` 사용 가능합니다!

2024-05-04 03:04 UTC, leehjhjhj commented on message/views/message_CRUD_views.py
> +    @swagger_auto_schema(manual_parameters=[authorization_header], request_body=MessageRequestSerializer, responses={"200":MessageResponseSerializer})
스웨거 아주 조하요..

2024-05-04 09:41 UTC, Zena0128 commented on message/domains/message_models.py
> +    send_id = models.ForeignKey(Member, null=False, on_delete=models.CASCADE, verbose_name='송신자', related_name='message_sender')
@leehjhjhj 
근데 회원 status가 활동, 정지, 탈퇴 이렇게 있으면 회원 객체 상태가 정지/탈퇴 수준을 넘어서서 삭제되는 경우에는 cascade로 삭제되어도 되지 않나요..?! 그래도 남겨놓는 것이 좋을까요??

2024-05-04 09:57 UTC, Zena0128 commented on message/domains/message_models.py
> +    body = models.TextField(default="", verbose_name='내용')
@leehjhjhj 
오 어떤 게 안되는거지 장고에서...
근데 찾아봤는데 charfield를 mysql에서 쓰면 영어 기준 최대 255자밖에 안 들어가는데,, 그러면 쪽지 길이 제한이 너무 크지는 않을까요?? 길게 쓰려면 길게 쓸 수도 있을 것 같아서..🤔

2024-05-04 10:10 UTC, Zena0128 commented on message/services/message_CRUD.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=receiver)
@leehjhjhj 
앗 근데 이거는 차단 목록에 없으면 메시지가 정상적으로 전송되게 처리하는 로직이라 404를 띄우면 안되지 않아요?!

2024-05-04 10:20 UTC, leehjhjhj commented on message/domains/message_models.py
> +    send_id = models.ForeignKey(Member, null=False, on_delete=models.CASCADE, verbose_name='송신자', related_name='message_sender')
그래도 있어야 하지 않을까요?? 특히나 센더나 리시버 한쪽만 지워도 없어지는 거라.. 🤔 fk관계를 끊는 것도 방법 일 수도 있겠네요

2024-05-04 10:21 UTC, leehjhjhj commented on message/domains/message_models.py
> +    body = models.TextField(default="", verbose_name='내용')
헉 그렇네요 ㅎㅎ ; 예전에 인덱스 걸 때 텍스트 필드가 말썽인 기억이 나서.. text field로 해야겠네요! 하나 알아 갑니다

2024-05-04 10:22 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=receiver)
어라 그렇네요. 로직을 다 이해하지 못했었네요. 좋습니다!

2024-05-04 10:25 UTC, Zena0128 commented on message/services/message_CRUD.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=receiver)
@leehjhjhj 저도 이해하기 쉽게 주석을 좀 더 열심히 달아야겠읍니다 .. 꼼꼼히 읽어주셔서 감사하여요   😊😊

2024-05-05 07:02 UTC, Zena0128 commented on message/services/message_block.py
> +        block = MessageBlock.objects.get(req_id=request.user, tar_id=target)
이것도 위의 것과 같은 맥락이라 넘어가도록 하겠읍니다 !

2024-05-07 23:43 UTC, leehjhjhj reviewed
고생하셨습니다! ‘.id’ 때문에 추가 쿼리 되는거 수정해주시고 ’__‘ 부분이 궁금해요!!

2024-05-07 23:43 UTC, leehjhjhj commented on message/serializers/message_serializer.py
> +            new_messages = Message.objects.filter(Q(sender__id = obj.sender.id) & Q(receiver__id = obj.receiver.id) & Q(is_read = False))
요기 sender__id 로 한 이유가 뭘까요?? message에 sender id가 있으니 sender_id로도 되지 않나요!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +    user_id = request.user.id
이거 request.user_id 로 변경하면 쿼리 한번 줄일 수 있어요!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        if message.receiver.id in partners or message.sender.id in partners:
이것도 receicer_id로 하면 추가 쿼리가 안나가요!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        if message.sender.id == user_id:
이것도!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        if message.receiver.id == user_id:
얘도!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        elif recent_message.receiver.id == user_id:
이것도!!

2024-05-07 23:43 UTC, leehjhjhj commented on message/services/message_CRUD.py
> +        recent_message = Message.objects.filter((Q(sender__id = partner_id) & Q(receiver__id = user_id)) | (Q(sender__id = user_id) & Q(receiver__id = partner_id))).order_by('-created_at')[0]
얘도 마찬가지로 __ 가 궁금합니다

2024-05-12 09:22 UTC, Zena0128 commented on message/serializers/message_serializer.py
> +            new_messages = Message.objects.filter(Q(sender__id = obj.sender.id) & Q(receiver__id = obj.receiver.id) & Q(is_read = False))
아ㅏㅏ drf가 fk 필드는 뒤에 _id를 붙여서 필드로 사용한단 사실을 망각한 이슈 입ㅂ니다 ,, 수정하겠습니다 !

2024-05-12 09:23 UTC, Zena0128 commented on message/services/message_CRUD.py
> +    user_id = request.user.id
이것도,,,! 위와 동일 이슈,,

2024-05-18 12:06 UTC, ShinSub98 commented on message/domains/__init__.py
여기서 다른 모델들을 임포트 하지 않은 이유가 있나요??

2024-05-18 12:08 UTC, ShinSub98 commented on message/serializers/__init__.py
여기도 시리얼라이저들을 임포트 하지 않은 이유가 궁금합니다!

2024-05-18 12:08 UTC, ShinSub98 commented on message/services/__init__.py
여기도 임포트 궁금해요!

2024-05-18 12:15 UTC, ShinSub98 commented on message/views/__init__.py
여기도!

2024-05-19 11:24 UTC, Zena0128 commented on message/domains/__init__.py
@ShinSub98 오모 아뇨.... init 파일의 역할을 모르고 있었어서 작성을 안했습니당. .. init파일에 임포트문들 추가해서 수정하도록 하겠습니당

2024-05-19 11:36 UTC, Zena0128 commented on message/domains/__init__.py
domain, serializer, service, view에서 init에 import 후 새로 커밋하였습니당

2024-05-22 13:32 UTC, ShinSub98 approved these changes
수고하셨습니다~

2024-05-22 23:22 UTC, leehjhjhj approved these changes
확인했습니다!! 고생많으셨어요!!!!

2024-05-23 01:38 UTC, Chaeyoung714 approved these changes
리뷰 반영한것까지 저도 확인했습니다! 고생하셨습니다

2024-05-24 00:09 UTC, leehjhjhj approved these changes
확인했습니다!

2024-05-24 11:38 UTC, merged