[FEAT] Message Push 알림 추가
LikeLion-11th-Domtory/Domtory_Server pull request #89
Opened 2024-07-08 14:14 UTC by leehjhjhj

### 작업한 내용
- 쪽지 전송시 알림 추가

2024-07-10 14:31 UTC, Zena0128 requested changes
고생하셨슴다~~ 삼일만에 뚝딱 하다니 짱짱
코멘트 하나만 확인 부탁드려여 !

2024-07-10 14:31 UTC, Zena0128 commented on push/services/push_services.py
> +            "messageRoomId": str(message.id)
이 부분 message가 아니라 messageRoom id를 보내야 하지 않나요?!

2024-07-11 00:03 UTC, leehjhjhj commented on push/services/push_services.py
> +            "messageRoomId": str(message.id)
oh~ 감사합니다 !! 고쳐서 올릴게요

2024-07-11 12:52 UTC, Chaeyoung714 approved these changes
확인했습니다! 고생하셨습니다압

2024-07-11 13:03 UTC, merged